import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed top-0 left-0 right-0 z-50 bg-black bg-opacity-30 text-white">
          <div className="container mx-auto px-6 py-4 grid grid-cols-3 items-center">
            {/* Kolom 1: Menu di Kiri */}
            <nav className="hidden md:flex items-center space-x-8 justify-self-start">
              <Link href="/" className="hover:text-gray-300">Tembi Resort</Link>
              <Link href="/rooms" className="hover:text-gray-300">Rooms</Link>
              <Link href="/Foods" className="hover:text-gray-300">Foods</Link>
            </nav>
            {/* Placeholder untuk mobile menu icon, jika diperlukan */}
            <div className="md:hidden justify-self-start">
                        {/* Anda bisa menambahkan icon hamburger menu di sini */}
            </div>

            {/* Kolom 2: Nama Website di Tengah */}
            <div className="text-center">
              <h1 className="text-xl font-bold font-serif">Tembi Resort</h1>
            </div>

            {/* Kolom 3: Tombol di Kanan */}
            <div className="justify-self-end">
              <a href="#" className="bg-primary hover:bg-primary-dark text-white font-semibold py-2 px-5 rounded-md transition-colors">
                        Book Now
              </a>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
